name = "MergeSort"
version = "0.1.0"
keywords = ["math"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false

[[lean_lib]]
name = "MergeSort"
buildType = "release"

[[lean_exe]]
name = "bench"
root = "RunBenchmarks"
buildType = "release"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "aesop"
scope = "leanprover-community"